const bibleVerses = [
    ["Isaiah 40:31", "But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint."],
    ["Philippians 4:6", "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God."],
    ["Psalm 23:1", "The LORD is my shepherd, I lack nothing."],
    ["Jeremiah 29:11", "For I know the plans I have for you, plans to prosper you and not to harm you, plans to give you hope and a future."],
    ["Philippians 4:13", "I can do all this through him who gives me strength."],
    ["Proverbs 3:5", "Trust in the LORD with all your heart and lean not on your own understanding."],
    ["Proverbs 18:10", "The name of the LORD is a fortified tower; the righteous run to it and are safe."],
    ["Romans 8:28", "And we know that in all things God works for the good of those who love him, who have been called according to his purpose."],
    ["Deuteronomy 31:6", "Be strong and courageous. Do not be afraid or terrified because of them, for the LORD your God goes with you; he will never leave you nor forsake you."],
    ["1 Peter 5:7", "Cast all your anxiety on him because he cares for you."],
    ["Matthew 11:28", "Come to me, all you who are weary and burdened, and I will give you rest."],
    ["Psalm 34:17-18", "The righteous cry out, and the LORD hears them; he delivers them from all their troubles. The LORD is close to the brokenhearted and saves those who are crushed in spirit."],
    ["John 14:27", "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid."],
    ["2 Corinthians 5:17", "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!"],
    ["Psalm 19:14", "May these words of my mouth and this meditation of my heart be pleasing in your sight, LORD, my Rock and my Redeemer."],
    ["Romans 15:13", "May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit."],
    ["Isaiah 41:10", "So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand."],
    ["Psalm 27:1", "The LORD is my light and my salvation—whom shall I fear? The LORD is the stronghold of my life—of whom shall I be afraid?"],
    ["Romans 12:2", "Do not conform to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God’s will is—his good, pleasing and perfect will."],
    ["Ephesians 2:8-9", "For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God—not by works, so that no one can boast."],
    ["Psalm 46:1", "God is our refuge and strength, an ever-present help in trouble."],
    ["1 Corinthians 16:14", "Do everything in love."],
    ["James 1:5", "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you."],
    ["Colossians 3:23-24", "Whatever you do, work at it with all your heart, as working for the Lord, not for human masters, since you know that you will receive an inheritance from the Lord as a reward. It is the Lord Christ you are serving."],
    ["Proverbs 16:3", "Commit to the LORD whatever you do, and he will establish your plans."],
    ["Galatians 5:22-23", "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control. Against such things there is no law."],
    ["Psalm 37:4", "Take delight in the LORD, and he will give you the desires of your heart."],
    ["John 3:16", "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life."],
];

export default bibleVerses;